### PR TITLE
Final0.8.0 geometry fix and tile_attribute moved to settings

### PR DESCRIPTION
**Pull request by ircwaves**
Request is as commented.  Ignore phone call....have a look and let me know if there are issues with what I have done.  Thanks.

### CODE REVIEW

**Comment by ircwaves** [comment]
The bug is that it didn't pass `gips/test/tile_geom.py`.  7bcbc94 makes it pass.

**Comment by ircwaves** [comment]
Looks like using `a.intersects(b)` is just as fast as `a.overlaps(b)`.  `a.intersection(b)` is ~20x slower.

```
In [17]: %timeit -n 10000 a.intersects(b)
10000 loops, best of 3: 12.4 µs per loop

In [18]: %timeit -n 10000 a.overlaps(b)
10000 loops, best of 3: 12.4 µs per loop

In [19]: %timeit -n 10000 a.intersection(b)
10000 loops, best of 3: 217 µs per loop

```

**Comment by ircwaves** [comment]
I didn't intend to push the changes to gipit/gips -- but it happened.  So, I won't issue a pull request. 

I will have to look at my `git` settings.  `git push` pushed to upstream, instead of origin.  Didn't think that was the default behaviour.

**Comment by matthewhanson** [comment]
Actually, i had pulled those changes into master, already, so you only wrote the (now defunct) final0.8.0 branch.   But no matter, I'll merge those with master

**Pull request closed without merging**
